name: Deploy to GitHub Pages via angular-cli-ghpages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Prepare and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run lint
          ###
          # Configure Angular first!
          ####
          # npm test --watch=false --progress=false --browsers=ChromeHeadlessCI
          # npm run webdriver-update-ci
          # npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js --webdriver-update=false
          ####
          npm run ng deploy --base-href=/website/ --name="github-actions" --email="action@github.com"
