name: CI Angular app through Github Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Setup
        run: npm ci

      - name: Test
        run: |
          npm test --no-watch --no-progress --browsers=ChromeHeadlessCI